// <auto-generated />
using System;
using EvChargingSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvChargingSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EvChargingSystem.API.Models.ChargingPoint", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PointId"));

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFunctional")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxPowerKw")
                        .HasColumnType("numeric");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.HasKey("PointId");

                    b.HasIndex("SiteId");

                    b.ToTable("ChargingPoints");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.ElectricityRate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RateId"));

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("numeric");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RateId");

                    b.HasIndex("SiteId");

                    b.ToTable("ElectricityRates");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiteId"));

                    b.Property<int>("AdministratorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SiteId");

                    b.HasIndex("AdministratorId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EnergyKwh")
                        .HasColumnType("numeric");

                    b.Property<int>("PointId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("PointId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.ChargingPoint", b =>
                {
                    b.HasOne("EvChargingSystem.API.Models.Site", "Site")
                        .WithMany("ChargingPoints")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.ElectricityRate", b =>
                {
                    b.HasOne("EvChargingSystem.API.Models.Site", "Site")
                        .WithMany("Rates")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.Site", b =>
                {
                    b.HasOne("EvChargingSystem.API.Models.User", "Administrator")
                        .WithMany("ManagedSites")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.Transaction", b =>
                {
                    b.HasOne("EvChargingSystem.API.Models.ChargingPoint", "ChargingPoint")
                        .WithMany("Transactions")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvChargingSystem.API.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.ChargingPoint", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.Site", b =>
                {
                    b.Navigation("ChargingPoints");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("EvChargingSystem.API.Models.User", b =>
                {
                    b.Navigation("ManagedSites");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
